development:
  adapter: postgresql
  database: skudenomination
  pool: 5
  timeout: 5000
  username: skudenomination
  password: skudenomination

test:
  adapter: postgresql
  database: skudenomination_test
  pool: 5
  timeout: 5000
  username: skudenomination
  password: skudenomination


production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
  username: skudenomination
  password: skudenomination
